name: Tag repo; build and publish assets
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        required: true
        default: false

jobs:
  tag-new-version:
    # This uses `conventional commits` to generate tags.  A full list
    # of valid prefixes is here:
    # https://github.com/commitizen/conventional-commit-types/blob/master/index.json)
    #
    # fix, perf -> patch release
    # feat -> minor release
    # BREAKING CHANGE in footer -> major release
    #
    # anything else (docs, refactor, etc) does not create a release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_version }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: tag
        uses: sebbacon/github-tag-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
